### ISSUE TITLE
请问执行make -j命令后报以下错误怎么解决呢？

### ISSUE THREAD

**Issue by Yolanda2020** [Tencent/ObjectDetection-OneStageDet#110]
$ make -j32
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 46, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME
make: *** [Makefile:2: all] Error 1

**Comment by Yolanda2020** [comment]
I use win10, so I changed the path of nvcc in code.
